In [8]:
import tensorflow as tf

In [9]:
matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]]) #This is a 3D matrix in tf

In [10]:
matrix.shape

TensorShape([3, 3])

In [11]:
matrix.dtype

tf.int32

In [12]:
matrix[:,1:] #Prints all rows and all columns barring the 0th column.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6],
       [8, 9]], dtype=int32)>

In [14]:
matrix = matrix + 10

In [15]:
tf.square(matrix)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[121, 144, 169],
       [196, 225, 256],
       [289, 324, 361]], dtype=int32)>

In [16]:
tf.transpose(matrix)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]], dtype=int32)>

In [17]:
#Attempting type conversion
mat1 = tf.constant([[1,2,3],[4,5,6]])
mat2 = tf.constant([[1., 2., 3.],[4.,5.,6.]])
print(mat1 + mat2)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 

In [20]:
mat = tf.Variable([[1,2],[4,5]])
mat

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

Creating a custom loss function

In [22]:
def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error)/2
    linear_loss = tf.abs(error) - 0.5
    return tf.where(is_small_error, squared_loss, linear_loss)
# Working of the tf.where() function. For each value in the output tensor, if is_small_error is true then squared loss is executed, else linear_loss is computed.

Custom activation function

In [23]:
def my_softplus(z):
    return tf.math.log(tf.exp(z) + 1.0)

Custom initialiser

In [24]:
def my_glorot(shape, dtype = tf.float32):
    stddev = tf.sqrt(2./ (shape[0] + shape[1]))
    return tf.random.normal(shape, stddev = stddev, dtype = dtype)